service: movie-booking-serverless-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 10
  environment:
    DYNAMODB_TABLE: ticket-booking
    AWS_ENDPOINT_URL: http://localstack:4566
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
    AWS_DEFAULT_REGION: us-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/ticket-booking"
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: "*"
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource: "*"

plugins:
  - serverless-python-requirements
  - serverless-localstack

custom:
  pythonRequirements:
    dockerizePip: non-linux
  
  localstack:
    stages:
      - local
    host: http://localhost
    autostart: false
    endpoints:
      S3: http://localhost:4566
      DynamoDB: http://localhost:4566
      CloudFormation: http://localhost:4566
      SNS: http://localhost:4566
      SQS: http://localhost:4566
      Lambda: http://localhost:4566
      ApiGateway: http://localhost:4566
    lambda:
      mountCode: true

functions:
  # GET Functions
  retrieveMovies:
    handler: handlers/get_handler.get_movies
    events:
      - http:
          path: /movies
          method: get
          cors: true

  retrieveTicket:
    handler: handlers/get_handler.get_ticket
    events:
      - http:
          path: /ticket
          method: get
          cors: true

  retrieveAllTickets:
    handler: handlers/get_handler.get_all_tickets
    events:
      - http:
          path: /tickets
          method: get
          cors: true

  # POST Function
  createTicket:
    handler: handlers/post_handler.create_ticket
    events:
      - http:
          path: /ticket
          method: post
          cors: true

  # PATCH Function
  updateTicket:
    handler: handlers/patch_handler.update_ticket
    events:
      - http:
          path: /ticket
          method: patch
          cors: true

  # DELETE Function
  removeTicket:
    handler: handlers/delete_handler.remove_ticket
    events:
      - http:
          path: /ticket
          method: delete
          cors: true

  # Event Handler Function
  priceChangeEventHandler:
    handler: handlers/event_handler.handle_price_change_event
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PriceChangeQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    PriceChangeTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-price-change-topic
        DisplayName: Movie Ticket Price Change Topic

    PriceChangeQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-price-change-queue
        VisibilityTimeout: 300
        MessageRetentionPeriod: 1209600
        ReceiveMessageWaitTimeSeconds: 20

    PriceChangeQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - ${self:service}-${self:provider.stage}-price-change-queue
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action: sqs:SendMessage
              Resource: 
                Fn::GetAtt:
                  - PriceChangeQueue
                  - Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref PriceChangeTopic

    PriceChangeSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        TopicArn: !Ref PriceChangeTopic
        Endpoint: 
          Fn::GetAtt:
            - PriceChangeQueue
            - Arn

  Outputs:
    PriceChangeTopic:
      Value: ${PriceChangeTopic}
    PriceChangeQueue:
      Value: ${PriceChangeQueue}

package:
  exclude:
    - node_modules/**
    - .git/**
    - .serverless/**
    - .env
    - volume/**
    - docker-compose.yml

