service: movie-booking-serverless-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  timeout: 10
  environment:
    DYNAMODB_TABLE: ticket-booking
    PRICE_CHANGE_TOPIC_ARN: !Ref PriceChangeTopic
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/ticket-booking"
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: !Ref PriceChangeTopic
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource: !GetAtt PriceChangeQueue.Arn

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  # GET Functions
  retrieveMovies:
    handler: handlers/get_handler.get_movies
    events:
      - http:
          path: /movies
          method: get
          cors: true

  retrieveTicket:
    handler: handlers/get_handler.get_ticket
    events:
      - http:
          path: /ticket
          method: get
          cors: true

  retrieveAllTickets:
    handler: handlers/get_handler.get_all_tickets
    events:
      - http:
          path: /tickets
          method: get
          cors: true

  # POST Function
  createTicket:
    handler: handlers/post_handler.create_ticket
    events:
      - http:
          path: /ticket
          method: post
          cors: true

  # PATCH Function
  updateTicket:
    handler: handlers/patch_handler.update_ticket
    events:
      - http:
          path: /ticket
          method: patch
          cors: true

  # DELETE Function
  removeTicket:
    handler: handlers/delete_handler.remove_ticket
    events:
      - http:
          path: /ticket
          method: delete
          cors: true

  # Event Handler Function - triggered by SQS
  priceChangeEventHandler:
    handler: handlers/event_handler.handle_price_change_event
    events:
      - sqs:
          arn: !GetAtt PriceChangeQueue.Arn
          batchSize: 1

resources:
  Resources:
    PriceChangeTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-price-change-topic
        DisplayName: Movie Ticket Price Change Topic

    PriceChangeQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-price-change-queue
        VisibilityTimeout: 300
        MessageRetentionPeriod: 1209600  # 14 days
        ReceiveMessageWaitTimeSeconds: 20  # Long polling

    PriceChangeQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref PriceChangeQueue
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action: sqs:SendMessage
              Resource: !GetAtt PriceChangeQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref PriceChangeTopic

    PriceChangeSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        TopicArn: !Ref PriceChangeTopic
        Endpoint: !GetAtt PriceChangeQueue.Arn

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.serverless/**'
    - '!.env'
    - '!package.json'
    - '!package-lock.json'